// Generated by LiveScript 1.2.0
var gulp, gulpUtil, gulpStylus, gulpLivescript, gulpLivereload, tinyLr, express, path, app, server, EXPRESSPORT, LIVERELOADPORT;
gulp = require('gulp');
gulpUtil = require('gulp-util');
gulpStylus = require('gulp-stylus');
gulpLivescript = require('gulp-livescript');
gulpLivereload = require('gulp-livereload');
tinyLr = require('tiny-lr');
express = require('express');
path = require('path');
app = express();
server = tinyLr();
EXPRESSPORT = 3001;
LIVERELOADPORT = 35729;
gulp.task('stylus', function(){
  return gulp.src('app/stylus/*.styl').pipe(gulpStylus()).pipe(gulp.dest('app/css')).pipe(gulpLivereload(server));
});
gulp.task('app', function(){
  return gulp.src('app/src/*.ls').pipe(gulpLivescript()).pipe(gulp.dest('app/js'));
});
gulp.task('youmeb', function(){
  gulp.src('app.ls').pipe(gulpLivescript()).pipe(gulp.dest('.'));
  gulp.src('api/controllers/*.ls').pipe(gulpLivescript()).pipe(gulp.dest('controllers'));
  gulp.src('api/models/*.ls').pipe(gulpLivescript()).pipe(gulp.dest('models'));
  return gulp.src('api/migrations/*.ls').pipe(gulpLivescript()).pipe(gulp.dest('migrations'));
});
gulp.task('express', function(){
  app.use(require('connect-livereload')());
  app.use(express['static'](path.resolve('.')));
  app.listen(EXPRESSPORT);
  return gulpUtil.log('Listening on port: ' + EXPRESSPORT);
});
gulp.task('watch', function(){
  return server.listen(LIVERELOADPORT, function(it){
    if (it) {
      return gulpUtil.log(it);
    }
    gulp.watch('app.ls', ['youmeb']);
    gulp.watch('api/**/*.ls', ['youmeb']);
    gulp.watch('app/stylus/*.styl', ['stylus']);
    return gulp.watch('app/src/*.ls', ['app']);
  });
});
gulp.task('default', ['stylus', 'app', 'watch', 'express', 'youmeb']);